/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDirectoryRouteImport } from './routes/_app/directory'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppGiveRouteImport } from './routes/_app/give'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppKidsRouteImport } from './routes/_app/kids'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppNewsRouteImport } from './routes/_app/news'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppResourcesRouteImport } from './routes/_app/resources'
import { Route as AppSermonsRouteImport } from './routes/_app/sermons'
import { Route as AppTeamsRouteImport } from './routes/_app/teams'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events.$eventId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppGiveRoute = AppGiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppKidsRoute = AppKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppSermonsRoute = AppSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/directory': typeof AppDirectoryRoute
  '/events': typeof AppEventsRouteWithChildren
  '/give': typeof AppGiveRoute
  '/groups': typeof AppGroupsRoute
  '/home': typeof AppHomeRoute
  '/kids': typeof AppKidsRoute
  '/messages': typeof AppMessagesRoute
  '/news': typeof AppNewsRoute
  '/profile': typeof AppProfileRoute
  '/resources': typeof AppResourcesRoute
  '/sermons': typeof AppSermonsRoute
  '/teams': typeof AppTeamsRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/directory': typeof AppDirectoryRoute
  '/events': typeof AppEventsRouteWithChildren
  '/give': typeof AppGiveRoute
  '/groups': typeof AppGroupsRoute
  '/home': typeof AppHomeRoute
  '/kids': typeof AppKidsRoute
  '/messages': typeof AppMessagesRoute
  '/news': typeof AppNewsRoute
  '/profile': typeof AppProfileRoute
  '/resources': typeof AppResourcesRoute
  '/sermons': typeof AppSermonsRoute
  '/teams': typeof AppTeamsRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/directory': typeof AppDirectoryRoute
  '/_app/events': typeof AppEventsRouteWithChildren
  '/_app/give': typeof AppGiveRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/kids': typeof AppKidsRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/sermons': typeof AppSermonsRoute
  '/_app/teams': typeof AppTeamsRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/directory'
    | '/events'
    | '/give'
    | '/groups'
    | '/home'
    | '/kids'
    | '/messages'
    | '/news'
    | '/profile'
    | '/resources'
    | '/sermons'
    | '/teams'
    | '/events/$eventId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/directory'
    | '/events'
    | '/give'
    | '/groups'
    | '/home'
    | '/kids'
    | '/messages'
    | '/news'
    | '/profile'
    | '/resources'
    | '/sermons'
    | '/teams'
    | '/events/$eventId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/directory'
    | '/_app/events'
    | '/_app/give'
    | '/_app/groups'
    | '/_app/home'
    | '/_app/kids'
    | '/_app/messages'
    | '/_app/news'
    | '/_app/profile'
    | '/_app/resources'
    | '/_app/sermons'
    | '/_app/teams'
    | '/_app/events/$eventId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/directory': {
      id: '/_app/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/give': {
      id: '/_app/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof AppGiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kids': {
      id: '/_app/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof AppKidsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sermons': {
      id: '/_app/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof AppSermonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teams': {
      id: '/_app/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppEventsRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppRouteChildren {
  AppDirectoryRoute: typeof AppDirectoryRoute
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppGiveRoute: typeof AppGiveRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppKidsRoute: typeof AppKidsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNewsRoute: typeof AppNewsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSermonsRoute: typeof AppSermonsRoute
  AppTeamsRoute: typeof AppTeamsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDirectoryRoute: AppDirectoryRoute,
  AppEventsRoute: AppEventsRouteWithChildren,
  AppGiveRoute: AppGiveRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppHomeRoute: AppHomeRoute,
  AppKidsRoute: AppKidsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNewsRoute: AppNewsRoute,
  AppProfileRoute: AppProfileRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSermonsRoute: AppSermonsRoute,
  AppTeamsRoute: AppTeamsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
